node('nodejs') {
  stage ('Build App'){
    openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')
  }
  
  stage ('Test App'){
    echo 'Starting Unit tests with Cucumber'
    sleep 5
    echo 'Passed tests'
  }
  
  stage ('Deploy Container'){
    openshiftDeploy(deploymentConfig: 'nodejs-ex')
  }
}
